define({
  root: {
    instructions: "Some instructions",
    addLayer: "Add Layer",
    mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
    button: "SET",
    instruction: "Unavailable Popup Message",
    defaultContent: "Add text, links, and small graphics here.",
    lookupLayersColumnText: "Lookup Layers",
    useColumnText: "Use",
    enableRefresh: "Enable Refresh",
    field: "Field",
    refreshInterval: "5 'Evaluated as time in Minutes'",
    alias: "Alias",
    visible: "Visible",
    linkField: "Link Field",
    noLayers: "No feature layers are available",
    back: "Back",
    restore: "Restore to default value",
    ok: "OK",
    result: "Saved successfully",
    warning: "Check to show the layer in the table first.",
    fieldCheckWarning: "At least one field must be selected.",
    unsupportQueryWarning: "The layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",
    unsupportQueryLayers: "The following layer needs to support query operation to display in Attribute Table widget. Make sure the query capability in the service is turned on.",
    fieldName: "Name",
    fieldAlias: "Alias",
    fieldVisibility: "Visibility",
    fieldActions: "Actions",
    mainPanelText: "Main Panel Text",
    mainPanelIcon: "Main Panel Image",
    nameText: "Display Name",
    iconColumnText: "Icon"

  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": false
});