define({
    root: {
        mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
        useColumnText: "Use",
        iconColumnText: "Icon",
        labelColumnText: "Display Name",
        refreshEnabled: "Enable Refresh",
        refreshInterval: "5 'Evaluated as time in Minutes'",
        noLayers: "No feature layers are available",
        mainPanelText: "Main Panel Text",
        mainPanelIcon: "Main Panel Image"
    },
    "ar": false,
    "cs": false,
    "da": false,
    "de": false,
    "es": false,
    "et": false,
    "fi": false,
    "fr": false,
    "he": false,
    "it": false,
    "ja": false,
    "ko": false,
    "lt": false,
    "lv": false,
    "nb": false,
    "nl": false,
    "pl": false,
    "pt-BR": false,
    "pt-PT": false,
    "ro": false,
    "ru": false,
    "sv": false,
    "th": false,
    "tr": false,
    "zh-cn": false
});